### ISSUE TITLE
Refactor to a new Example

### ISSUE THREAD

**Issue by willianjusten** [lyef/lyef-react-counter#1]
Foo and bar are horrible thing to show, we need something better.

**Comment by willianjusten** [comment]
@nipher

**Comment by jmpas** [comment]
I'll change it to something like this:
`<Counter start={10} end={0} done={cb} />`

**Comment by willianjusten** [comment]
Nice =)
It's far far better than just Foo list.

**Comment by willianjusten** [comment]
Done on #10
